import {
    LucideArrowLeft,
    LucideBookmark,
    LucideBug,
    LucideCalendar,
    LucideChartLine,
    LucideCheck,
    LucideChevronDown,
    LucideChevronLeft,
    LucideChevronRight,
    LucideChevronUp,
    LucideChevronsDown,
    LucideChevronsUp,
    LucideCircleAlert,
    LucideCircleCheck,
    LucideClock,
    LucideColumns3,
    LucideCopy,
    LucideEllipsisVertical,
    LucideEqual,
    LucideGitBranch,
    LucideIcon,
    LucideInfo,
    LucideLayoutDashboard,
    LucideList,
    LucideMenu,
    LucideMessageSquare,
    LucidePaperclip,
    LucidePencil,
    LucidePlus,
    LucideSearch,
    LucideSettings,
    LucideSquareCheck,
    LucideTag,
    LucideTrash2,
    LucideTriangleAlert,
    LucideUser,
    LucideX,
    LucideZap,
} from '@lucide/angular'

export const LUCIDE_ICONS: LucideIcon[] = [
    LucideArrowLeft,
    LucideBookmark,
    LucideBug,
    LucideCalendar,
    LucideChartLine,
    LucideCheck,
    LucideChevronDown,
    LucideChevronLeft,
    LucideChevronRight,
    LucideChevronUp,
    LucideChevronsDown,
    LucideChevronsUp,
    LucideCircleAlert,
    LucideCircleCheck,
    LucideClock,
    LucideColumns3,
    LucideCopy,
    LucideEllipsisVertical,
    LucideEqual,
    LucideGitBranch,
    LucideInfo,
    LucideLayoutDashboard,
    LucideList,
    LucideMenu,
    LucideMessageSquare,
    LucidePaperclip,
    LucidePencil,
    LucidePlus,
    LucideSearch,
    LucideSettings,
    LucideSquareCheck,
    LucideTag,
    LucideTrash2,
    LucideTriangleAlert,
    LucideUser,
    LucideX,
    LucideZap,
]

export const ICONS = {
    // Issue types
    epic: 'zap',
    story: 'bookmark',
    task: 'square-check',
    bug: 'bug',
    subtask: 'git-branch',

    // Priorities
    'priority-highest': 'chevrons-up',
    'priority-high': 'chevron-up',
    'priority-medium': 'equal',
    'priority-low': 'chevron-down',
    'priority-lowest': 'chevrons-down',

    // Actions
    add: 'plus',
    edit: 'pencil',
    delete: 'trash-2',
    close: 'x',
    check: 'check',
    copy: 'copy',
    more: 'ellipsis-vertical',

    // Navigation
    back: 'arrow-left',
    menu: 'menu',
    search: 'search',
    'chevron-up': 'chevron-up',
    'chevron-down': 'chevron-down',
    'chevron-left': 'chevron-left',
    'chevron-right': 'chevron-right',

    // App sections
    dashboard: 'layout-dashboard',
    board: 'columns-3',
    backlog: 'list',
    roadmap: 'calendar',
    reports: 'chart-line',
    settings: 'settings',

    // Status
    error: 'circle-alert',
    warning: 'triangle-alert',
    success: 'circle-check',
    info: 'info',

    // Issue detail
    assignee: 'user',
    label: 'tag',
    attachment: 'paperclip',
    comment: 'message-square',
    time: 'clock',
} as const

export type IconName = keyof typeof ICONS
